name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name  }}
          body: |
            See [CHANGES.md](https://github.com/holgerbrandl/kortools/blob/master/CHANGES.md) for new features, bug-fixes and changes.
          draft: false
          prerelease: false

permissions:
  contents: write